# Site
title:              GINGER
bio:                '你好'
description:        '我是Ginger'
reading_time:       false
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/IMGP7363.jpg'
tiled_bg:           false
locale:             zh_tw
url:                https://brainginger.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            false
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   brainginger

# Social
#google:
  #plus:            #username
  #analytics:
email:              landy51223@yahoo.com.tw
facebook:           landy51223
#linkedin:          username
instagram:          brainginger

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
